name: deployment
on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd projects/backend
            git pull
            docker build -t fl-api .
            docker stop fl-api
            docker run --name fl-api --rm --detach --mount source=fl-data,target=/app/data --mount type=bind,source=/home/${{ secrets.USERNAME }}/projects/backend/config.json,target=/app/config.json --network fl -p 23001:18000 fl-api
