name: Go pipeline
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: install deps
        run: go get -u 

      - name: build
        run: go build -v ./...
